version: '3.9'

services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_media
      db_host: database
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  # app:
  #   build: .
  #   container_name: social_media
  #   ports:
  #     - "3333:3333"
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - database

volumes:
  mysql-data:
    driver: local
